#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source /usr/share/yunohost/helpers

#=================================================
# INITIALIZE AND STORE SETTINGS
#=================================================

email=$(ynh_user_get_info --username="$admin" --key="mail")
firstname=$(ynh_user_get_info --username="$admin" --key="firstname")
lastname=$(ynh_user_get_info --username="$admin" --key="lastname")
timezone=$(timedatectl show --value --property=Timezone)

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

# Download, check integrity, uncompress and patch the source from manifest.toml
ynh_setup_source --dest_dir="$install_dir"

usermod -g www-data "$app"

#=================================================
# APP INITIAL CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration files..."

ynh_config_add --template=".env.example" --destination="$install_dir/.env"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

# Create a PHP-FPM config (with conf/extra_php-fpm.conf being appended to it)
ynh_config_add_phpfpm

# Create a dedicated NGINX config using the conf/nginx.conf template
ynh_config_add_nginx

ynh_config_add --template="cron" --destination="/etc/cron.d/$app"

#=================================================
# FINAL FREESCOUT INSTALL
#=================================================
ynh_script_progression "Finalizing $app installation..."

pushd "$install_dir"
    "php$php_version" artisan key:generate --no-interaction --force
    "php$php_version" artisan freescout:clear-cache
    "php$php_version" artisan storage:link
    "php$php_version" artisan migrate --no-interaction --force
    "php$php_version" artisan freescout:create-user --role="admin" --firstName="$firstname" --lastName="$lastname" --email="$email" --password="$password" --no-interaction

    chgrp -R www-data storage bootstrap/cache public/css/builds public/js/builds
    chmod -R ug+rwx storage bootstrap/cache public/css/builds public/js/builds
popd

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
