#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# INITIALIZE AND STORE SETTINGS
#=================================================

email=$(ynh_user_get_info --username="$admin" --key="mail")
firstname=$(ynh_user_get_info --username="$admin" --key="firstname")
lastname=$(ynh_user_get_info --username="$admin" --key="lastname")

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Upgrading source files..."

# FIXME: use --full_replace
ynh_safe_rm "$install_dir/vendor"

ynh_setup_source --dest_dir="$install_dir" --keep=".env" #--full_replace

#REMOVEME? Assuming the install dir is setup using ynh_setup_source, the proper chmod/chowns are now already applied and it shouldn't be necessary to tweak perms | chmod -R o-rwx "$install_dir"
#REMOVEME? Assuming the install dir is setup using ynh_setup_source, the proper chmod/chowns are now already applied and it shouldn't be necessary to tweak perms | chown -R "$app:www-data" "$install_dir"
#=================================================
# REAPPLY SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

ynh_config_add_phpfpm

ynh_config_add_nginx

#=================================================
# FINAL FREESCOUT INSTALL
#=================================================
ynh_script_progression "Install $app"

pushd "$install_dir"
    "php$php_version" artisan freescout:clear-cache
    "php$php_version" artisan migrate --no-interaction --force
popd

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
