#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# INITIALIZE AND STORE SETTINGS
#=================================================

email=$(ynh_user_get_info --username="$admin" --key="mail")
firstname=$(ynh_user_get_info --username="$admin" --key="firstname")
lastname=$(ynh_user_get_info --username="$admin" --key="lastname")

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression --message="Upgrading source files..." --weight=1

# FIXME: use --full_replace=1
ynh_secure_remove --file="$install_dir/vendor"

ynh_setup_source --dest_dir="$install_dir" --keep=".env" #--full_replace=1

chmod -R o-rwx "$install_dir"
chown -R "$app:www-data" "$install_dir"

#=================================================
# REAPPLY SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression --message="Upgrading system configurations related to $app..." --weight=1

ynh_add_fpm_config

ynh_add_nginx_config

#=================================================
# FINAL FREESCOUT INSTALL
#=================================================
ynh_script_progression --message="Install $app" --weight=5

pushd "$install_dir"
    "php$phpversion" artisan freescout:clear-cache
    "php$phpversion" artisan migrate --no-interaction --force
popd

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Upgrade of $app completed" --last
